# Generated by Django 4.2.2 on 2023-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_cliente_producto_factura_cliente_factura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
